-- Create core tables for marriage card ordering system
-- Migration: 20250301170900_create_core_tables.sql

-- Create marriage_card_type_details table
CREATE TABLE IF NOT EXISTS public.marriage_card_type_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    card_type TEXT NOT NULL CHECK (card_type IN ('Normal', 'VIP', 'VVIP')),
    size TEXT NOT NULL,
    gsm TEXT NOT NULL,
    price DECIMAL(10,2) NOT NULL CHECK (price >= 0),
    available_stock INTEGER NOT NULL DEFAULT 0 CHECK (available_stock >= 0),
    max_stock INTEGER NOT NULL DEFAULT 1000 CHECK (max_stock >= 0),
    minimum_order_quantity INTEGER NOT NULL DEFAULT 1 CHECK (minimum_order_quantity >= 1),
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create marriage_card_details table
CREATE TABLE IF NOT EXISTS public.marriage_card_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_type_id BIGINT NOT NULL REFERENCES public.marriage_card_type_details(id) ON DELETE RESTRICT,
    children_message TEXT DEFAULT '',
    welcomers JSONB DEFAULT '[]'::jsonb,
    aspirations JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create marriage_person_details table
CREATE TABLE IF NOT EXISTS public.marriage_person_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_detail_id BIGINT NOT NULL REFERENCES public.marriage_card_details(id) ON DELETE CASCADE,
    person_type TEXT NOT NULL CHECK (person_type IN ('Bride', 'Groom', 'Janew')),
    name TEXT NOT NULL,
    father_name TEXT NOT NULL,
    mother_name TEXT NOT NULL,
    address TEXT NOT NULL,
    profession_name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create event_details table
CREATE TABLE IF NOT EXISTS public.event_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_detail_id BIGINT NOT NULL REFERENCES public.marriage_card_details(id) ON DELETE CASCADE,
    event_name TEXT NOT NULL,
    event_date DATE NOT NULL,
    event_location TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create arranger_details table
CREATE TABLE IF NOT EXISTS public.arranger_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_detail_id BIGINT NOT NULL REFERENCES public.marriage_card_details(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    mobile_number TEXT NOT NULL,
    address TEXT NOT NULL,
    profession_name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_marriage_card_type_details_card_type ON public.marriage_card_type_details(card_type);
CREATE INDEX IF NOT EXISTS idx_marriage_card_type_details_price ON public.marriage_card_type_details(price);
CREATE INDEX IF NOT EXISTS idx_marriage_card_type_details_available_stock ON public.marriage_card_type_details(available_stock);
CREATE INDEX IF NOT EXISTS idx_marriage_card_details_card_type_id ON public.marriage_card_details(card_type_id);
CREATE INDEX IF NOT EXISTS idx_marriage_person_details_card_detail_id ON public.marriage_person_details(card_detail_id);
CREATE INDEX IF NOT EXISTS idx_event_details_card_detail_id ON public.event_details(card_detail_id);
CREATE INDEX IF NOT EXISTS idx_arranger_details_card_detail_id ON public.arranger_details(card_detail_id);

-- Enable RLS (Row Level Security)
ALTER TABLE public.marriage_card_type_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marriage_card_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marriage_person_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.arranger_details ENABLE ROW LEVEL SECURITY;

-- Policies for marriage_card_type_details (public read, admin write)
CREATE POLICY "Anyone can view card types" 
    ON public.marriage_card_type_details FOR SELECT 
    USING (true);

CREATE POLICY "Only admins can insert card types" 
    ON public.marriage_card_type_details FOR INSERT 
    WITH CHECK (auth.jwt() ->> 'role' = 'admin');

CREATE POLICY "Only admins can update card types" 
    ON public.marriage_card_type_details FOR UPDATE 
    USING (auth.jwt() ->> 'role' = 'admin');

CREATE POLICY "Only admins can delete card types" 
    ON public.marriage_card_type_details FOR DELETE 
    USING (auth.jwt() ->> 'role' = 'admin');

-- Policies for marriage_card_details (users can view their own, admins all)
CREATE POLICY "Users can view their own card details" 
    ON public.marriage_card_details FOR SELECT 
    USING (EXISTS (
        SELECT 1 FROM public.orders 
        WHERE orders.card_type_id = marriage_card_details.card_type_id 
        AND (orders.user_id = auth.uid() OR auth.jwt() ->> 'role' = 'admin')
    ));

CREATE POLICY "Users can insert their own card details" 
    ON public.marriage_card_details FOR INSERT 
    WITH CHECK (EXISTS (
        SELECT 1 FROM public.orders 
        WHERE orders.card_type_id = marriage_card_details.card_type_id 
        AND (orders.user_id = auth.uid() OR guest_email IS NOT NULL)
    ));

-- Policies for other detail tables follow similar pattern
CREATE POLICY "Users can view their own person details" 
    ON public.marriage_person_details FOR SELECT 
    USING (EXISTS (
        SELECT 1 FROM public.marriage_card_details cd
        JOIN public.orders o ON o.card_type_id = cd.card_type_id
        WHERE cd.id = marriage_person_details.card_detail_id
        AND (o.user_id = auth.uid() OR auth.jwt() ->> 'role' = 'admin')
    ));

CREATE POLICY "Users can view their own event details" 
    ON public.event_details FOR SELECT 
    USING (EXISTS (
        SELECT 1 FROM public.marriage_card_details cd
        JOIN public.orders o ON o.card_type_id = cd.card_type_id
        WHERE cd.id = event_details.card_detail_id
        AND (o.user_id = auth.uid() OR auth.jwt() ->> 'role' = 'admin')
    ));

CREATE POLICY "Users can view their own arranger details" 
    ON public.arranger_details FOR SELECT 
    USING (EXISTS (
        SELECT 1 FROM public.marriage_card_details cd
        JOIN public.orders o ON o.card_type_id = cd.card_type_id
        WHERE cd.id = arranger_details.card_detail_id
        AND (o.user_id = auth.uid() OR auth.jwt() ->> 'role' = 'admin')
    ));

-- Create trigger to update updated_at timestamp for marriage_card_type_details
CREATE OR REPLACE FUNCTION public.update_marriage_card_type_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_marriage_card_type_details_updated_at
    BEFORE UPDATE ON public.marriage_card_type_details
    FOR EACH ROW EXECUTE FUNCTION public.update_marriage_card_type_updated_at();

-- Create trigger to update updated_at timestamp for marriage_card_details
CREATE OR REPLACE FUNCTION public.update_marriage_card_details_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_marriage_card_details_updated_at
    BEFORE UPDATE ON public.marriage_card_details
    FOR EACH ROW EXECUTE FUNCTION public.update_marriage_card_details_updated_at();

-- Insert some sample card types for testing
INSERT INTO public.marriage_card_type_details (name, card_type, size, gsm, price, available_stock, max_stock, minimum_order_quantity) VALUES
('Royal Gold', 'VIP', '5x7', '300', 25.00, 100, 500, 50),
('Elegant Silver', 'Normal', '5x7', '250', 15.00, 200, 1000, 100),
('Platinum Elite', 'VVIP', '6x8', '350', 40.00, 50, 200, 25),
('Classic Ivory', 'Normal', '5x7', '275', 18.00, 150, 800, 75),
('Diamond Bliss', 'VIP', '6x8', '325', 32.00, 75, 300, 50)
ON CONFLICT DO NOTHING;