-- Create user_profiles table for storing user roles and additional user data
-- Migration: 20250301171100_create_user_profiles_role.sql

-- Create role enum
CREATE TYPE public.user_role AS ENUM (
    'user',
    'admin'
);

-- Create user_profiles table
CREATE TABLE IF NOT EXISTS public.user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    role public.user_role NOT NULL DEFAULT 'user',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Ensure one profile per user
    UNIQUE(user_id)
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_user_profiles_user_id ON public.user_profiles(user_id);
CREATE INDEX IF NOT EXISTS idx_user_profiles_role ON public.user_profiles(role);

-- Enable RLS
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;

-- RLS Policies for user_profiles
-- Users can view their own profile
CREATE POLICY "Users can view their own profile"
    ON public.user_profiles FOR SELECT
    USING (auth.uid() = user_id);

-- Users can update their own profile (except role)
CREATE POLICY "Users can update their own profile"
    ON public.user_profiles FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Only admins can insert profiles (but we have trigger for new users)
CREATE POLICY "Only admins can insert profiles"
    ON public.user_profiles FOR INSERT
    WITH CHECK (EXISTS (
        SELECT 1 FROM public.user_profiles up
        WHERE up.user_id = auth.uid() AND up.role = 'admin'
    ));

-- Function to handle new user signup - creates profile with default 'user' role
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.user_profiles (user_id, role)
    VALUES (NEW.id, 'user');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to create user profile after user signup
CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Function to get user role for use in policies
CREATE OR REPLACE FUNCTION public.get_user_role(user_id UUID)
RETURNS public.user_role AS $$
DECLARE
    user_role public.user_role;
BEGIN
    SELECT role INTO user_role
    FROM public.user_profiles
    WHERE user_profiles.user_id = $1;
    
    RETURN COALESCE(user_role, 'user'::public.user_role);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to check if user is admin (for JWT compatibility)
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.user_profiles
        WHERE user_id = auth.uid() AND role = 'admin'
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Update existing policies that use auth.jwt() ->> 'role' = 'admin'
-- We'll create helper functions and update policies in separate migration
-- but we need to update the JWT to include role claim

-- Function to update JWT claims with user role
CREATE OR REPLACE FUNCTION public.update_jwt_claims()
RETURNS JSONB AS $$
DECLARE
    claims JSONB;
BEGIN
    claims := jsonb_build_object(
        'role', (SELECT role FROM public.user_profiles WHERE user_id = auth.uid())
    );
    RETURN claims;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_user_profiles_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_user_profiles_updated_at
    BEFORE UPDATE ON public.user_profiles
    FOR EACH ROW EXECUTE FUNCTION public.update_user_profiles_updated_at();

-- Insert admin role for existing users who should be admins
-- You can manually update specific users to admin role after migration
-- Example: UPDATE public.user_profiles SET role = 'admin' WHERE user_id = 'your-admin-user-uuid';

-- Create default admin user if needed (optional - uncomment and set email)
-- DO $$
-- DECLARE
--     admin_user_id UUID;
-- BEGIN
--     SELECT id INTO admin_user_id FROM auth.users WHERE email = 'admin@example.com';
--     IF FOUND THEN
--         INSERT INTO public.user_profiles (user_id, role)
--         VALUES (admin_user_id, 'admin')
--         ON CONFLICT (user_id) DO UPDATE SET role = 'admin';
--     END IF;
-- END $$;